name: generic_clf_env
channels:
  - defaults
dependencies:
  - conda
  - python=3.7
  - menuinst
  - console_shortcut
  - powershell_shortcut
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda==2019.10=py37_0
  - anaconda-navigator==1.9.12
  - navigator-updater
  - scikit-learn
  - scikit-optimize
  - hyperopt
  - imbalanced-learn
  - flask
  - pandas-profiling
  - mysql-connector-python